/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repuesto_controler;

import codigo.proCode;
import java.awt.Image;
import java.io.File;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.proModel;
import Conexion.conexion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import modelo.menuModel;
/**
 *
 * @author coron
 */
public class Pro extends javax.swing.JFrame {
    private byte[] imagenBytes;
    conexion a = new conexion();
    Connection conect;
    private Menu_principal mp;
    proCode pc = new proCode();
    proModel pm = new proModel();
    String id;
    int id_marca = 0;
    private int mod;
    private String rutaImagenSeleccionada;
    
    public Pro() {
        this.conect = a.conectar();
        initComponents();
        pc.marcas(marca_combo);
        marca_combo.addActionListener((actionEvt) -> {
            JComboBox comboBox = (JComboBox) actionEvt.getSource();
            Map<String, Integer> mapMarca = (Map<String, Integer>) comboBox.getClientProperty("mapMarca");
            String marca = (String) comboBox.getSelectedItem();
            pm.setId_marca(mapMarca.get(marca));
        });
        centrar();
    }
    
    public Pro(Menu_principal mp1) {
        this.mp = mp1;
        this.conect = a.conectar();
        initComponents();
        pc.marcas(marca_combo);
        marca_combo.addActionListener((actionEvt) -> {
            JComboBox comboBox = (JComboBox) actionEvt.getSource();
            Map<String, Integer> mapMarca = (Map<String, Integer>) comboBox.getClientProperty("mapMarca");
            String marca = (String) comboBox.getSelectedItem();
            pm.setId_marca(mapMarca.get(marca));
            id_marca = pm.getId_marca();
        });
        centrar();
        
    }
    
    private void centrar(){
        Dimension tamaño = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (tamaño.width - this.getWidth()) / 2;
        int y = (tamaño.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }
    
    public void modos(int modo){
        this.mod = modo;
        if(mod != 1){
            marca_ref.setVisible(false);
        }
        else{
            marca_ref.setEditable(false);
        }
    }
    
    public void datos(String id, String nombre, String marca, int idM, String precio){
        this.id_marca = idM;
        this.id = id;
        nombreTXT.setText(nombre);
        marca_ref.setText(marca);
        precioTXT.setText(precio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreTXT = new javax.swing.JTextField();
        precioTXT = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        añadir_foto = new javax.swing.JButton();
        marca_combo = new javax.swing.JComboBox<>();
        boton_subir = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        marca_ref = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de productos");
        setResizable(false);

        nombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTXTActionPerformed(evt);
            }
        });

        precioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTXTActionPerformed(evt);
            }
        });

        foto.setBackground(new java.awt.Color(153, 0, 153));
        foto.setText("           No selecciono una foto");
        foto.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Foto: ");

        añadir_foto.setBackground(new java.awt.Color(51, 255, 51));
        añadir_foto.setText("Añadir");
        añadir_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir_fotoActionPerformed(evt);
            }
        });

        boton_subir.setBackground(new java.awt.Color(51, 255, 51));
        boton_subir.setText("Subir");
        boton_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_subirActionPerformed(evt);
            }
        });

        boton_salir.setBackground(new java.awt.Color(255, 255, 153));
        boton_salir.setText("Volver");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foto, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(añadir_foto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(precioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marca_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(marca_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(boton_subir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(boton_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(marca_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(añadir_foto)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_subir)
                    .addComponent(boton_salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTXTActionPerformed

    private void nombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTXTActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombreTXTActionPerformed

   
    private void boton_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_subirActionPerformed

        String nombreProducto = nombreTXT.getText().trim();
        String precioProducto = precioTXT.getText().trim();

        if (nombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete el campo Nombre del producto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precioProducto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete el campo Precio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id_marca == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una marca.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            if (conect != null) {
                if(mod == 0){
                    if (imagenBytes == null) {
                        JOptionPane.showMessageDialog(null, "Por favor, seleccione una imagen para el producto.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    String sql = "INSERT INTO productos (marca, nombre_producto, precio, foto) VALUES (?, ?, ?, ?)";
                    try (PreparedStatement ps = conect.prepareStatement(sql)) {
                        ps.setInt(1, id_marca); 
                        ps.setString(2, nombreProducto);
                        ps.setBigDecimal(3, new BigDecimal(precioProducto));
                        if (imagenBytes != null) {
                            ps.setBytes(4, imagenBytes);
                        } 
                        else {
                            ps.setNull(4, java.sql.Types.BLOB);
                        }

                        int rowsInserted = ps.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(null, "¡Un nuevo producto fue insertado exitosamente!");
                            mp.repuestosCargados();
                            id_marca = 0;
                        }
                    }
                }
                else{
                    String sql = "UPDATE productos SET marca = ?, nombre_producto = ?, precio = ? WHERE id = ?";
                    try (PreparedStatement ps = conect.prepareStatement(sql)) {
                        ps.setInt(1, id_marca); 
                        ps.setString(2, nombreProducto);
                        ps.setString(3,precioProducto);
                        ps.setString(4, id);
                        int rowsInserted = ps.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(null, "¡Se modificó el producto con exito!");
                            mp.repuestosCargados();
                            dispose();
                        }
                    }
                }
            } else {
               
            }
            nombreTXT.setText("");
            precioTXT.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "La imagen es muy pesada. Solo se aceptan imagenes de hasta 1 MB", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_boton_subirActionPerformed
    
     
    private void añadir_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir_fotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes JPG & PNG", "jpg", "png");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String rutaImagen = selectedFile.getAbsolutePath();

            Path path = Paths.get(rutaImagen);
            try {
                imagenBytes = Files.readAllBytes(path);
                ImageIcon icon = new ImageIcon(imagenBytes);

                Image img = icon.getImage();
                Image resizedImg = img.getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_SMOOTH);
                icon = new ImageIcon(resizedImg);
                foto.setText("");
                foto.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Pro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó ninguna imagen", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_añadir_fotoActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadir_foto;
    private javax.swing.JButton boton_salir;
    private javax.swing.JButton boton_subir;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> marca_combo;
    private javax.swing.JTextField marca_ref;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JTextField precioTXT;
    // End of variables declaration//GEN-END:variables

    void setProducto(String nombreProducto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
